steps:
  - name: fast-build devshells
    image: bash
    commands:
      - set -e
      - nix develop --show-trace
      # - nix-fast-build -f .#devShells.x86_64-linux.default --skip-cached --systems x86_64-linux --result-file /tmp/resultfile
      # - print "Results"
      # - cat /tmp/resultfile

  - name: fast-build packages
    image: bash
    commands:
      - set -e
      # BUG: CI is building aarch64 when it shouldn't
      # - nix-fast-build -f .#packages --no-nom --skip-cached
      # - nix-fast-build -f .#packages --no-nom --skip-cached --systems x86_64-linux --result-file /tmp/resultfile
      # BUG: above workaround insufficient to stop eval failures: https://github.com/Mic92/nix-fast-build/issues/29
      - nix-fast-build -f .#packages.x86_64-linux --no-nom --skip-cached --result-file /tmp/resultfile
      - print "Results"
      - cat /tmp/resultfile

  - name: fast-build all hosts
    image: bash
    commands:
      - set -e
      # BUG: CI is building aarch64 when it shouldn't
      # - nix-fast-build -f .#hosts.toplevels --no-nom --skip-cached
      - nix-fast-build -f .#hosts.toplevels --no-nom --skip-cached --systems x86_64-linux --result-file /tmp/resultfile
      - print "Results"
      - cat /tmp/resultfile

  - name: fast-build checks
    image: bash
    commands:
      # BUG: CI is building aarch64 when it shouldn't
      # - nix-fast-build -f .#checks --no-nom --skip-cached
      # - nix-fast-build -f .#checks --no-nom --skip-cached --systems x86_64-linux --result-file /tmp/resultfile
      # BUG: above workaround insufficient to stop eval failures: https://github.com/Mic92/nix-fast-build/issues/29
      - nix-fast-build -f .#checks.x86_64-linux --no-nom --skip-cached --result-file /tmp/resultfile
      - print "Results"
      - cat /tmp/resultfile

  # some hosts can't be eval-ed only, must be built
  # - name: nix flake check (eval only)
  #   image: bash
  #   commands:
  #     - nix flake check --no-build --show-trace
  #   when:
  #     - event: pull_request
  #     - event: push
  #       branch: master
