[btrfs-list]
src.github_tag = "speed47/btrfs-list"
fetch.github = "speed47/btrfs-list"

[nushell-latest]
src.github_tag = "nushell/nushell"
fetch.github = "nushell/nushell"

[nushell-master]
src.git = "https://github.com/nushell/nushell"
fetch.github = "nushell/nushell"
