# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  btrfs-list = {
    pname = "btrfs-list";
    version = "v2.2";
    src = fetchFromGitHub {
      owner = "speed47";
      repo = "btrfs-list";
      rev = "v2.2";
      fetchSubmodules = false;
      sha256 = "sha256-JtTqhf0fsbPYeUkRAvgdH6CgoRUJXKAZv32i+pyf6AY=";
    };
  };
  nushell-latest = {
    pname = "nushell-latest";
    version = "0.90.1";
    src = fetchFromGitHub {
      owner = "nushell";
      repo = "nushell";
      rev = "0.90.1";
      fetchSubmodules = false;
      sha256 = "sha256-MODd2BT2g6g5H6/1EG5OjIoYm18yBSvYTR83RuYDMec=";
    };
  };
  nushell-master = {
    pname = "nushell-master";
    version = "68fcd71898f97cf635956ede83ed33be25eebfd7";
    src = fetchFromGitHub {
      owner = "nushell";
      repo = "nushell";
      rev = "68fcd71898f97cf635956ede83ed33be25eebfd7";
      fetchSubmodules = false;
      sha256 = "sha256-ZDtK0Xjwql1HlrEA7x5lwtLnbl8I10E0bpg2/2sPOLw=";
    };
    date = "2024-02-18";
  };
}
